CREATE DATABASE MVC1_PRACTICE;
USE MVC1_PRACTICE;

CREATE TABLE BOARD (
	BOARD_ID 	BIGINT AUTO_INCREMENT PRIMARY KEY,
    WRITER 		VARCHAR(50),
    EMAIL 		VARCHAR(50),
    SUBJECT 	VARCHAR(100),
    PASSWORD 	VARCHAR(20),
   	CONTENT     VARCHAR(2000),
    READ_CNT    BIGINT,
   	ENROLL_DT 	TIMESTAMP
);

ALTER TABLE BOARD AUTO_INCREMENT = 100000;